event_management/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path("",home,name="events")
]

main/urls.py
from django.urls import path
from .views import *

from django.shortcuts import redirect
app_name="main"
<<<<<<< HEAD:website/main/urls.py
=======

>>>>>>> 9ed7c20ed86faf17738664a45e3cee59583088cb:main/urls.py
urlpatterns=[
    path("",home,name="home"),
    path("downloads/",lambda request: redirect("1/"),name="downloads"),
    path("downloads/<int:page>/",downloads,name="downloads"),
    path("contact/",contact,name="contacts"),
    path("staff_enquiry/",staff_details,name="staff"),
    
    path("dashboard/",dashboard,name="dashboard"),
    path("download_file/<int:path>",download_file,name="download_file")
]

website/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("main.urls")),
    path("event_management/",include("event_management.urls"))
]

event_management/models.py
from django.db import models

class MenuItem(models.Model):
    item_name=models.CharField(max_length=50)
    item_price=models.IntegerField()

    def __str__(self):
        return self.item_name

class Event(models.Model):
    name_of_dept=models.CharField(max_length=50)
    date_of_indent=models.DateField()
    date_of_arrangement=models.DateField()
    
    No_of_person=models.IntegerField()
    menu=models.ManyToManyField(to=MenuItem)
    payment_status=models.IntegerField(choices=[(1,"paid"),(0,"pending")])

main/models.py
from django.db import models
import datetime
# Create your models here.
class Article(models.Model):
    descr=models.CharField(max_length=100)
    file=models.FileField(upload_to="uploads/")
    uploaded_at=models.DateField(auto_now_add=True)
                    
    def __str__(self):
        return self.descr

event_management/views.py
from django.shortcuts import render
from .models import Event
# Create your views here.
def home(request):
    obj=Event.objects.all()
    ctx={"Events":obj}
    return render(request,"event_management/index.html",ctx)

main/views.py
from django.shortcuts import render
from .models import Article
import os
from django.conf import settings
from django.http import HttpResponse, Http404
from django.core.paginator import Paginator
# Create your views here.
def home(request):
    return render(request,"main/index.html")

def contact(request):
    return render(request,"main/contact.html")

def staff_details(request):
    return render(request,"main/staff.html")

def downloads(request,page):
    articles=Article.objects.all().order_by("-uploaded_at")
    paginator=Paginator(articles,8)
    page_object = paginator.get_page(page)
    context = {"page_obj": page_object}
    return render(request,"main/downloads.html",context=context)

def download_file(request, path):
    file_object=Article.objects.get(pk=path)
    response = HttpResponse(file_object.file, content_type='application/force-download')
    response['Content-Disposition'] = f'attachment; filename="{file_object.file.name}"'
    return response

def dashboard(request):
    return render(request,"main/dashboard.html")

templates/event_management/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1> Paid </h1>
<ul>
    {% for Event in Events %}
        {% if Event.payment_status == 1 %}
            <li>{{ Event.name_of_dept }}</li>
        {% endif %}
    {% endfor %}
</ul>

<h1> Unpaid </h1>
<ul>
    {% for Event in Events %}
        {% if Event.payment_status != 1 %}
            <li>{{ Event.name_of_dept }}</li>
        {% endif %}
    {% endfor %}
</ul>


</body>
</html>

templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/main/style.css'%}">
    {% comment %} <script src="{% static 'javascript/script.js'%}"> {% endcomment %}
</head>
<body>
    <div class="header">
        <img src="{% static 'images/66953057.jpg'%}" class="sign">
        <h1 style="margin:0%;">DELHI TECHNOLOGICAL UNIVERSITY</h1>
        <p>formerly Delhi College of Engineering<br>(Under Delhi Act of 2009, Govt. of NCT of Delhi)<br>Accredited with 'A' Grade (CGPA 3.22 out of 4.0) by NAAC(1st Cycle)<br>ISO 9001:2015 Certified</p>
        </div>
          <div class="navbar">
            <a href="{% url "main:home" %}" class="active">Home</a>
            <a href="http://www.dtu.ac.in/" target="_blank">Official site of DTU</a>
            <a href="{% url "main:contacts" %}">Contact us</a>
            <a href="{% url "main:home" %}">Feedback</a>
            <a href="log in" id="log">Log in</a>
          </div>
          <div class="grid-container">
            <div class="grid-item item1"><h4 style="color: #ddd;">Inside the website</h4>
            <div class="dropdown">
              <h5 button class="dropbtn">About Gen. Admin</h5>
            <div class="dropdown-content">
              <a href="/homepage.html">About gen. admin</a>
              <a href="{% url "main:staff" %}">Staff</a>
              <a href="{% url "main:staff" %}">Staff Intercoms</a>
            </div></div>
            <div class="side">
            <a href="{% url "main:downloads" %}"><h5>Downloads</h5></a>
            <h5>Work Distribution</h5>
            <h5>Sop. of Gen. Admin</h5>
            <h5>abcd</h5></div></div>
    {% block body %}{% endblock body %}
    <div class="grid-item item3"><h4>Notices</h4></div> 
    
</body>

<script>
{% block script %}{% endblock script %}
</script>
</html>

templates/main/contact.html
{% extends "main/base.html" %}

{% block title %} Contact{% endblock title %}

{% block body %}
<div class="grid-item item2">
  <center> <h1>CONTACT US</h1></center>
  <h3>Deputy Registrar/ Section Officer

   (Gen. Administration)
   
   Delhi Technological University
   
   Admn. Building
   
   Shahbad Daulatpur, Bawana Road,
   
   Delhi-110042
   
   Email: ga@dtu.ac.in
   
   Phone: 011-27294673 (Direct)
   
   Ext. 1108</h3>
   <footer>Happy to Serve DTU Community</footer>
</div>

{% endblock body %}
    

templates/main/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    dashboard
</body>
</html>

templates/main/downloads.html
{% extends "main/base.html" %}

{% block title %} Contact{% endblock title %}

{% block body %}
<div class="grid-item item2">
    {% with articles=page_obj.object_list.all %}
    ARTICLES:
    <table border="1px">
        <tr>
            <th>Description</th>
            <th>Date</th>
            <th>file</th>
        <tr>
        {% for article in articles %}
        
            <td>
                <p>{{article.descr}}</p>
            </td>
            <td>
                {{article.uploaded_at}}
            </td>
            <td><a href="{% url 'main:download_file' article.id %}">
                download
            </a></td>
            
        </tr>
        {% endfor %}
    </table>
    {% endwith %}    

    {% block pagination %}
    {% for page_number in page_obj.paginator.page_range %}
        <a
            href="{% url 'main:downloads' page_number %}"
            class="{% if page_number == page_obj.number %}current{% endif %}"
        >
            {{page_number}}
        </a>
    {% endfor %}
{% endblock %}
<footer>Happy to Serve DTU Community</footer>
    </div>  
{% endblock body %}

templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block title %} Homepage{% endblock title %}
{%block body%}<div class="grid-item item2"><h1>Welcome to the webpage of general administration</h1>
        
  <p>General Administration is undeniably one of the foundational pillars of any university, seamlessly facilitating its operations with a myriad of indispensable services. Among these essential services are the provision of outsourced manpower, crucial for maintaining the day-to-day functioning of various departments and ensuring smooth operations across the campus. Additionally, the cleaning manpower provided by the General Administration ensures a hygienic and conducive environment for both students and faculty members alike, promoting a healthy and productive academic atmosphere.

    Furthermore, the General Administration branch extends its support through the management of EPBX systems, facilitating effective communication channels within the university community. Moreover, the administration diligently handles the reimbursement of bills for basic facilities availed by faculty members and officers, ensuring their essential needs are met promptly and efficiently. This commitment to service extends to the arrangement of hospitality for visiting dignitaries and guests, reflecting the university's commitment to fostering meaningful connections and collaborations.
    
    Beyond these tangible services, the General Administration branch also plays a pivotal role in organizing university functions and events, ensuring their seamless execution from conception to completion. Each member of the General Administration team is dedicated to serving the university community with passion and a warm smile, embodying the ethos of hospitality and professionalism.
    
    Moreover, the General Administration branch operates in alignment with the core values of the university, upholding principles of integrity, excellence, and inclusivity in all its endeavors. It is not merely a duty but a privilege for the staff to contribute towards fulfilling the vision and mission of the university, striving to exceed expectations and set new standards of service excellence.
    
    In essence, the General Administration branch serves as the backbone of the university, tirelessly working behind the scenes to support and enhance the academic and administrative endeavors of the institution. With their unwavering dedication and commitment to excellence, the staff of the General Administration branch exemplify the spirit of service and contribute significantly to the overall success and reputation of the university.
  </p>
  
  <div class="slideshow-container">

    <div class="mySlides fade">
      <img src="{% static 'images/dtu1.png'%}" style="width:100%; height:400px">
    </div>
    
    <div class="mySlides fade">
      <img src="{% static 'images/dtu2.png'%}" style="width:100%; height:400px">
    </div>
    
    <div class="mySlides fade">
      <img src="{% static 'images/dtu3.png'%}" style="width:100%; height:400px">
    </div>
    
    </div>
    <br>
    
    <div style="text-align:center">
      <span class="dot"></span> 
      <span class="dot"></span> 
      <span class="dot"></span> 
    </div>

    <footer>Happy to Serve DTU Community</footer>
</div>

{% comment %} <script type="javascript" href="{% static 'javascript/script.js' %}"> {% endcomment %}
  {% endblock body %}


{% block script %}


    console.log("hello");

    let slideIndex = 0;
    showSlides();
    
    function showSlides() {
        let i;
        let slides = document.getElementsByClassName("mySlides");
        let dots = document.getElementsByClassName("dot");
        for (i = 0; i < slides.length; i++) {
        slides[i].style.display = "none";  
        }
        slideIndex++;
        if (slideIndex > slides.length) {slideIndex = 1}    
        for (i = 0; i < dots.length; i++) {
        dots[i].className = dots[i].className.replace(" active", "");
        }
        slides[slideIndex-1].style.display = "block";  
        dots[slideIndex-1].className += " active";
        setTimeout(showSlides, 2000); // Change image every 2 seconds
    }
    

{% endblock script %}
  

templates/main/staff.html
{% extends "main/base.html" %}

{% block title %} Contact{% endblock title %}

{% block body %}
<div class="grid-item item2"><h1>Important Circulars/ Forms/Office Orders of General Administration</h1>
            
    <table><tr><th>Sr. no</th><th>Branch incharge/staff details</th><th>Inter com.</th></tr>
   <tr><td>1.</td><td>Mr. Anil Kumar, Dy. Registrar</td><td>011-27294673 (Direct) / Ext. 1106</td></tr>
   <tr><td>2.</td><td>Mr. Chander Prakash, Sr. Office Asstt.</td><td>1145</td></tr>
   <tr><td>3.</td><td>Ms. Brijna, Jr. Office Asstt.</td><td>2730</td></tr>
   <tr><td>4.</td><td>Mr. Kunal, Jr. Office Asstt.</td><td>2727</td></tr>
   <tr><td>5.</td><td>Mr. Inderjeet, ,Jr. Office Asstt.</td><td>2728</td></tr>
   <tr><td>6.</td><td>Ms. Nazmin, STA</td><td>1108</td></tr>
   <tr><td>7.</td><td>Mr. Vikram, MTS            </td><td>2728</td></tr></table>
   <footer>Happy to Serve DTU Community</footer>   
</div>
   {%endblock body %}

templates/main/staffinq.html
{% extends "main/base.html" %}

{% block title %} Contact{% endblock title %}

{% block body %}
<center><div class="grid-item item2"><h1>Important Circulars/ Forms/Office Orders of General Administration</h1>
            
    <table><tr><th>Sr. no</th><th>Branch incharge/staff details</th><th>Inter com.</th></tr>
   <tr><td>1.</td><td>Mr. Anil Kumar, Dy. Registrar</td><td>011-27294673 (Direct) / Ext. 1106</td></tr>
   <tr><td>2.</td><td>Mr. Chander Prakash, Sr. Office Asstt.</td><td>1145</td></tr>
   <tr><td>3.</td><td>Ms. Brijna, Jr. Office Asstt.</td><td>2730</td></tr>
   <tr><td>4.</td><td>Mr. Kunal, Jr. Office Asstt.</td><td>2727</td></tr>
   <tr><td>5.</td><td>Mr. Inderjeet, ,Jr. Office Asstt.</td><td>2728</td></tr>
   <tr><td>6.</td><td>Ms. Nazmin, STA</td><td>1108</td></tr>
   <tr><td>7.</td><td>Mr. Vikram, MTS            </td><td>2728</td></tr></table>
   <footer>Happy to Serve DTU Community</footer>   
</div></center>
   {%endblock body %}